name: Build module .so's

on:
  # release:
  #   types: [created]
  push:
    branches:
      - master # FIXME: remove once works

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx:
          - 0.1.45
          - 0.2.6
          - 0.3.61
          - 0.4.14
          - 0.5.38
          - 0.6.39
          - 0.7.69
          - 0.8.55
          - 0.9.7
          - 1.0.15
          - 1.1.19
          - 1.2.9
          - 1.3.16
          - 1.4.7
          - 1.5.13
          - 1.6.3
          - 1.7.12
          - 1.8.1
          - 1.9.15
          - 1.10.3
          - 1.11.13
          - 1.12.2
          - 1.13.12
          - 1.14.2
          - 1.15.12
          - 1.16.1
          - 1.17.10
          - 1.18.0
          - 1.19.10
          - 1.20.2
          - 1.21.6
          - 1.22.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download nginx
        run: |
          curl https://nginx.org/download/nginx-${{ matrix.nginx}}.tar.gz -o nginx.tar.gz
      - name: Extract nginx
        run: |
          tar -xzvf nginx.tar.gz -o
      - name: Change directory into nginx
        run: |
          cd nginx-${{ matrix.nginx }}
      - name: Configure nginx
        run: |
          ./configure --add-dynamic-module=..
      - name: Build modules
        run: |
          make modules
