name: Build module .so's

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx:
          - 1.9.15
          - 1.10.3
          - 1.11.13
          - 1.12.2
          - 1.13.12
          - 1.14.2
          - 1.15.12
          - 1.16.1
          - 1.17.10
          - 1.18.0
          - 1.19.10
          - 1.20.2
          - 1.21.6
          - 1.22.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download nginx
        run: |
          curl https://nginx.org/download/nginx-${{ matrix.nginx}}.tar.gz -o nginx.tar.gz
      - name: Extract nginx
        run: |
          tar -xzvf nginx.tar.gz -o
      - name: Build modules
        run: |
          cd nginx-${{ matrix.nginx }}
          ./configure --add-dynamic-module=..
          make modules
          cp objs/shardeb_module.so ../shardeb-${{ github.event.release.tag_name }}-nginx-${{ matrix.nginx }}
      - name: Edit release
        uses: svenstaro/upload-release-action@v2
        with:
          file: shardeb-*.so
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
